version: '2'
services:

  registry:
    image: registry:2
    ports: 
      - 5000:5000
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"
    restart: always
    volumes:
      - ./data:/var/lib/registry
    networks:
      distribution:
        aliases:
          - registry
          
networks:
  distribution:
    driver: 'bridge'