version: '2'
services:

  front:
    image: simple-nginx
    networks:
      projet-1:
        aliases:
          - front
    ports:
      - ${SIMPLE_NGINX_EXTERNAL_PORT}:80
    command: "bash-tail"
    volumes:
      - ./front/etc/nginx:/etc/nginx:ro
      - ./front/var/www/app:/var/www/app
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

networks:
  projet-1:
    driver: "bridge"