version: '2'
services:

  proxy:
    image: simple-haproxy
    networks:
      projet-1:
        aliases:
          - proxy
    depends_on:
      - front
      - back
    ports:
      - ${PROXY_EXTERNAL_PORT}:80
      - ${PROXY_EXTERNAL_PORT_SSL}:443
      - ${PROXY_STATS_EXTERNAL_PORT}:80
    command: "bash-tail"
    volumes:
      - ./proxy/etc/haproxy:/etc/haproxy:ro
      - ./proxy/etc/logrotate.d:/etc/logrotate.d:ro
      - ./proxy/etc/rsyslog:/etc/rsyslog:ro
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"
