version: '2'
services:

# ELK
 base_debian_java8: 
  build: ./desc/base_debian_java8
# Log stash is useless beacause it's replace by beat 
# logstash:
#  build: ./desc/logstash
#  depends_on:
#   - base_debian_java8
 elasticsearch:
  build: ./desc/elasticsearch
  depends_on:
   - base_debian_java8

# Stranges things ...
 base_debian_dev: 
  build: ./desc/base_debian_dev
 base_debian_beat: 
  build: ./desc/base_debian_beat
  depends_on: 
  - base_debian_dev
  - elasticsearch
 base_debian_nginx: 
  build: ./desc/base_debian_nginx
  depends_on:
   - base_debian_beat
  links:
   - elasticsearch
 web:
  build: ./desc/ngnix
  depends_on:
   - base_debian_nginx
  ports:
   - "80:80"
