version: "2"
services:
  
  jenkins:
    image: jenkins:2.7.4
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      ci:
        aliases:
          - jenkins
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

networks:
  ci:
    driver: "bridge"
